import React, {useState} from 'react';
import Typist from 'react-typist';
import './../Styles/Abyss.css';
import Jellyfish from './../all-images/jellyfish copy.png';
import Starfish from './../all-images/starfish.png';
import Bottle from './../all-images/plastic-bottle.png';
import Microplastic from './../all-images/microplastic.png';

function Abyss(props){

    const [showJellyfishBubble, setShowJellyfishBubble] = useState(false);    
    const [showStarfishBubble, setShowStarfishBubble] = useState(false);    
    const [showBottleBubble, setShowBottleBubble] = useState(false);    

    return(
        <div className ='Abyss'>
            <Typist cursor={{show:false, hideWhenDone:true}} >
                <h1 className='abyssTitle'>Abyss Layer</h1>
            </Typist>
        <img alt='' src={Bottle} className='bottleImage2'/>
        <div id='jellyfish' className='jellyfishContainer'>
            <img alt='' src={Jellyfish} className='jellyfishImage' 
                // listeners
                onMouseEnter={() => setShowJellyfishBubble(true)}
                onMouseLeave={() => setShowJellyfishBubble(false)}
            />
            {showJellyfishBubble ? 
                // if true
                <h2 className='jellyfishLabel'>
                    Noise pollution generated by shipping and military activity can cause cellular damage to a class of invertebrates that includes jellyfish and anemones.
                </h2>:
                // if false
                <h1>
                    {/* emptiness */}
                </h1>
            }
        </div>
        <img alt='' src={Bottle} className='bottleImage'/>
        <div id='starfish' className='starfishContainer'>
            <img alt='' src={Starfish} className='starfishImage' 
                // listeners
                onMouseEnter={() => setShowStarfishBubble(true)}
                onMouseLeave={() => setShowStarfishBubble(false)}
            />
            {showStarfishBubble ? 
                // if true
                <h2 className='starfishLabel'>
                    The deepest place on Earth (6.8 miles to a point in the Mariana Trench) was discovered to host trash. 
                </h2>:
                // if false
                <h1>
                    {/* emptiness */}
                </h1>
            }
        </div>
        <img alt='' src={Microplastic} className='microplasticAbyss'/>
    </div>
    )
                
    
}
export default Abyss